name: ClashFactory Config Generator

on:
  schedule:
    - cron: '0 0 * * *'  # اجرا هر روز
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  generate-configs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Files/requirements.txt
      - name: Run ClashFactory
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          python Files/main.py || echo "main.py failed, continuing with extract_configs.py"
          python Files/extract_configs.py
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update configs and README" || echo "No changes to commit"
          git push
